In [35]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from src.scrappy import Scrappy

pd.set_option('future.no_silent_downcasting', True)

s = Scrappy(
        funds_overview_path='data/funds_overview.csv',
        performance_path='data/performance.csv',
        timeseries_path='data/timeseries.csv'
    )

benchmarks = ['IE00B5BMR087', 'DE000A0F5UF5', 'IE0005042456', 'DE0006289390', 'DE0005933931', 'LU0340285161']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

INFO:src.scrappy:Loaded funds_overview data from data/funds_overview.csv
INFO:src.scrappy:Loaded performance data from data/performance.csv
INFO:src.scrappy:Loaded timeseries data from data/timeseries.csv

In [33]:

renten_eu = [5531,5674,5676,5673,5647,5646,5620,5576,5670,5677]
renten_all = [5634,5532,5645,5620,5670,5560,5646,5647,5531,5672,
              5673,5674,5676,5677,5648,5643,5534,5644,5570,5678,
              5679,5680,5535,5681,5581,5625,5651,5654,5622,5652,
              5557,5684,5685,5653,5558]
s.download_funds_overview(benchmark=True)
s.download_funds_overview(limit=2000, etf=False)
s.download_funds_overview(limit=1000, etf=True)
s.download_funds_overview(limit=17000, filter_ids=renten_all, etf=False)
s.download_funds_overview(limit=2000, filter_ids=renten_all, etf=True)

s.extract_performance()

s.save_funds_overview('data/funds_overview.csv')
s.save_performance('data/performance.csv')

INFO:src.scrappy:Successfully downloaded 55 funds
INFO:src.scrappy:Successfully downloaded 1940 funds
INFO:src.scrappy:Successfully downloaded 201 funds
INFO:src.scrappy:Successfully downloaded 2000 funds
INFO:src.scrappy:Successfully downloaded 1001 funds

In [3]:
s.download_timeseries(benchmarks)
s.save_timeseries('data/timeseries.csv')

INFO:src.scrappy:Parsing timeseries data...
WARNING:src.scrappy:Failed to parse data for IE00B5BMR087: malformed node or string on line 1: <ast.Call object at 0x7ddc91a0f710>, use eval
WARNING:src.scrappy:Failed to parse data for DE000A0F5UF5: malformed node or string on line 1: <ast.Call object at 0x7ddc92651350>, use eval
WARNING:src.scrappy:Failed to parse data for IE0005042456: malformed node or string on line 1: <ast.Call object at 0x7ddc937655d0>, use eval
WARNING:src.scrappy:Failed to parse data for DE0006289390: malformed node or string on line 1: <ast.Call object at 0x7ddc91eb3ed0>, use eval
WARNING:src.scrappy:Failed to parse data for DE0005933931: malformed node or string on line 1: <ast.Call object at 0x7ddc8d5c3310>, use eval
WARNING:src.scrappy:Failed to parse data for LU0340285161: malformed node or string on line 1: <ast.Call object at 0x7ddc902be150>, use eval

In [57]:
filters = {
        'initial_fee': '<=1.0', # Ausgabeaufschlag
        'fund_type': 'Thesaurierend',
        'sparplan_finanzen_zero': True,
    }

criteria = {'performanceTimeSpanPct': 0.0, 
            'sharpeRatio': 2.0, 
            'volatility': -0.0, 
            'maxDrawdown': -0.0, 
            'TER': -0.0}

filtered_isins = s.filter_funds(filters)[['name', 'initial_fee', 'sparplan_finanzen_zero']].index

s.rank_funds(criteria=criteria, timespan='5Y', isins=filtered_isins, limit=20)

INFO:src.scrappy:After filtering initial_fee with <=1.0: 2050 funds remaining
INFO:src.scrappy:After filtering fund_type with Thesaurierend: 1338 funds remaining
INFO:src.scrappy:After filtering sparplan_finanzen_zero with True: 240 funds remaining

INFO:src.scrappy:Using pre-extracted performance data for ranking
INFO:src.scrappy:Ranked 20 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
IE00BDFGJ627,iShares USD Floating Rate Bond UCITS ETF USD Acc.,15.7005,53.9821,0.3905,-0.7224,0.10000,2.000000
LU1681040900,Amundi Floating Rate USD Corporate ESG UCITS E...,15.6808,32.8800,0.6424,-1.0708,0.18000,1.256269
LU1681041114,Amundi Floating Rate Euro Corporate ESG UCITS ...,10.0965,29.8775,0.3911,-1.5864,0.18000,1.150448
LU0613540268,Xtrackers II Italy Government Bond 0-1 Swap UC...,6.3677,29.4942,0.2667,-1.7777,0.15000,1.136939
LU1681041031,Amundi Floating Rate USD Corporate ESG UCITS E...,10.7440,18.9191,0.6499,-2.5249,0.20000,0.764226
IE00BZ173W74,iShares USD Corporate Bond Interest Rate Hedge...,30.3118,9.7010,3.7759,-6.1189,0.25000,0.439339
IE00BF3N7094,iShares Euro High Yield Corporate Bond UCITS E...,23.8639,8.2425,3.3155,-14.8253,0.50000,0.387935
LU1109943388,Xtrackers II EUR High Yield Corporate Bond UCI...,24.3499,8.2008,3.2955,-14.7749,0.23300,0.386465
IE00BZ17CN18,iShares USD Short Duration High Yield Corporat...,26.1921,8.0776,4.0477,-7.4236,0.45000,0.382123
IE00BGYWSV06,Vanguard USD Corporate 1-3 years Bond UCITS ET...,8.2106,7.8779,1.6947,-6.4456,0.09001,0.375085
IE00BJK55C48,iShares EUR High Yield Corporate Bond ESG UCIT...,21.0994,7.2989,3.3442,-16.5105,0.25000,0.354679
IE00B57X3V84,iShares Dow Jones Global Sustainability Screen...,82.6097,6.5631,14.2208,-27.3334,0.60000,0.328746
IE00BFY0GT14,SPDR MSCI World UCITS ETF USD Acc.,90.5183,6.5235,14.9727,-25.9038,0.12000,0.327350
IE00BJ0KDQ92,Xtrackers MSCI World UCITS ETF 1C USD Acc.,89.5117,6.4273,15.0355,-26.0896,0.19300,0.323959
IE00B5BMR087,iShares Core S&P 500 UCITS ETF USD Acc.,100.8820,6.1955,17.8239,-24.6153,0.07000,0.315790
IE00BFMXXD54,Vanguard S&P 500 UCITS ETF USD Acc.,100.7830,6.1717,17.4780,-24.6166,0.07007,0.314951
IE00BZ02LR44,Xtrackers MSCI World ESG UCITS ETF 1C USD Acc.,89.9316,6.1575,15.6578,-28.9594,0.20000,0.314451
IE00BHZPJ569,iShares MSCI World ESG Enhanced UCITS ETF USD ...,82.4912,6.0206,15.3977,-28.0188,0.20000,0.309626
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,102.5980,5.8768,17.8847,-26.7592,0.09200,0.304557
IE00BJK55B31,iShares USD High Yield Corporate Bond ESG UCIT...,23.3578,5.8678,5.0919,-15.7902,0.25000,0.304240

In [58]:
# rank by strategies
filters = {
        'initial_fee': '<=1.0', # Ausgabeaufschlag
        'fund_type': 'Thesaurierend',
        'sparplan_finanzen_zero': True,
    }
filtered_isins = s.filter_funds(filters)[['name', 'initial_fee', 'sparplan_finanzen_zero']].index

print("conservative")
display(s.rank_funds_by_strategy(timespan='5Y', isins=filtered_isins, strategy='conservative'))
print("growth")
display(s.rank_funds_by_strategy(timespan='5Y', isins=filtered_isins, strategy='growth'))
print("balanced")
display(s.rank_funds_by_strategy(timespan='5Y', isins=filtered_isins, strategy='balanced'))
print("long_term")
display(s.rank_funds_by_strategy(timespan='5Y', isins=filtered_isins, strategy='long_term'))
print("short_term")
display(s.rank_funds_by_strategy(timespan='1Y', isins=filtered_isins, strategy='short_term'))

INFO:src.scrappy:After filtering initial_fee with <=1.0: 2050 funds remaining
INFO:src.scrappy:After filtering fund_type with Thesaurierend: 1338 funds remaining
INFO:src.scrappy:After filtering sparplan_finanzen_zero with True: 240 funds remaining
INFO:src.scrappy:Using conservative strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking

INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

conservative

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
IE00BDFGJ627,iShares USD Floating Rate Bond UCITS ETF USD Acc.,15.7005,53.9821,0.3905,-0.7224,0.100,3.270504
LU1287023268,Amundi Euro Government Bond 15+ years UCITS ET...,-31.9118,-2.1673,14.0786,-46.0075,0.150,3.247382
IE00BH04GW44,Vanguard UK Gilt UCITS ETF GBP Acc.,-27.4498,-2.7470,11.1652,-38.5882,0.070,3.200900
IE00BZ171348,iShares Global AAA-AA Government Bond UCITS ET...,-14.0359,-1.1509,8.4536,-32.7796,0.200,3.011041
LU1920015440,Xtrackers II USD Emerging Markets Bond UCITS E...,2.9847,1.0429,7.2126,-30.0199,0.256,2.982281
LU0950674332,UBS ETF MSCI World Socially Responsible UCITS ...,80.7660,5.5386,16.0520,-32.5243,0.220,2.914363
LU1650489385,Amundi Euro Government Bond 10-15 years UCITS ...,-14.9135,-1.4907,8.9981,-29.9812,0.150,2.909537
LU2089238625,Amundi EUR Corporate Bond UCITS ETF Acc.,2.4295,1.0769,3.8193,-18.0347,0.070,2.893990
LU2089238898,Amundi Prime Euro Govies UCITS ETF EUR Acc.,-9.9874,-1.3933,6.0749,-22.3293,0.050,2.892142
IE00BFM6TB42,iShares Global Corporate Bond UCITS ETF USD Acc.,-0.3492,0.7421,6.1642,-25.0901,0.200,2.884060

INFO:src.scrappy:Using growth strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking
INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

growth

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
IE00BM67HX07,Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged,109.7770,5.4712,17.6155,-25.9211,0.09100,2.847120
IE00BYVQ9F29,iShares NASDAQ-100 UCITS ETF EUR Acc. Hedged,136.1720,4.2649,24.7371,-37.6626,0.36000,2.841011
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,102.5980,5.8768,17.8847,-26.7592,0.09200,2.773568
IE00BFMXXD54,Vanguard S&P 500 UCITS ETF USD Acc.,100.7830,6.1717,17.4780,-24.6166,0.07007,2.766345
IE00B5BMR087,iShares Core S&P 500 UCITS ETF USD Acc.,100.8820,6.1955,17.8239,-24.6153,0.07000,2.763831
FR0010655712,Amundi ETF DAX UCITS ETF DR EUR Acc.,102.2950,5.8196,18.0073,-26.7774,0.10000,2.757490
IE00B53SZB19,iShares NASDAQ-100 UCITS ETF USD Acc.,123.4780,5.3329,23.9418,-35.2751,0.33000,2.730234
DE0005933931,iShares Core DAX UCITS ETF EUR Acc. (DE),101.7340,5.7833,17.8503,-26.7745,0.16000,2.675680
LU0252633754,Amundi DAX III UCITS ETF EUR Acc.,101.9480,5.5186,18.9277,-26.7951,0.15000,2.673476
IE00BFY0GT14,SPDR MSCI World UCITS ETF USD Acc.,90.5183,6.5235,14.9727,-25.9038,0.12000,2.631395

INFO:src.scrappy:Using balanced strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking
INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

balanced

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
IE00BDFGJ627,iShares USD Floating Rate Bond UCITS ETF USD Acc.,15.7005,53.9821,0.3905,-0.7224,0.10000,3.707042
LU1681040900,Amundi Floating Rate USD Corporate ESG UCITS E...,15.6808,32.8800,0.6424,-1.0708,0.18000,2.847409
LU0613540268,Xtrackers II Italy Government Bond 0-1 Swap UC...,6.3677,29.4942,0.2667,-1.7777,0.15000,2.742528
LU1681041114,Amundi Floating Rate Euro Corporate ESG UCITS ...,10.0965,29.8775,0.3911,-1.5864,0.18000,2.726847
IE00BM67HX07,Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged,109.7770,5.4712,17.6155,-25.9211,0.09100,2.640076
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,102.5980,5.8768,17.8847,-26.7592,0.09200,2.621111
IE00BFMXXD54,Vanguard S&P 500 UCITS ETF USD Acc.,100.7830,6.1717,17.4780,-24.6166,0.07007,2.616777
IE00B5BMR087,iShares Core S&P 500 UCITS ETF USD Acc.,100.8820,6.1955,17.8239,-24.6153,0.07000,2.608509
FR0010655712,Amundi ETF DAX UCITS ETF DR EUR Acc.,102.2950,5.8196,18.0073,-26.7774,0.10000,2.602595
IE00BFY0GT14,SPDR MSCI World UCITS ETF USD Acc.,90.5183,6.5235,14.9727,-25.9038,0.12000,2.594660

INFO:src.scrappy:Using long_term strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking

long_term

INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
IE00BDFGJ627,iShares USD Floating Rate Bond UCITS ETF USD Acc.,15.7005,53.9821,0.3905,-0.7224,0.10000,4.056102
IE00BFMXXD54,Vanguard S&P 500 UCITS ETF USD Acc.,100.7830,6.1717,17.4780,-24.6166,0.07007,3.602168
IE00B5BMR087,iShares Core S&P 500 UCITS ETF USD Acc.,100.8820,6.1955,17.8239,-24.6153,0.07000,3.598156
IE00BM67HX07,Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged,109.7770,5.4712,17.6155,-25.9211,0.09100,3.589699
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,102.5980,5.8768,17.8847,-26.7592,0.09200,3.554141
FR0010655712,Amundi ETF DAX UCITS ETF DR EUR Acc.,102.2950,5.8196,18.0073,-26.7774,0.10000,3.519678
IE00BFY0GT14,SPDR MSCI World UCITS ETF USD Acc.,90.5183,6.5235,14.9727,-25.9038,0.12000,3.416949
LU0252633754,Amundi DAX III UCITS ETF EUR Acc.,101.9480,5.5186,18.9277,-26.7951,0.15000,3.312846
DE0005933931,iShares Core DAX UCITS ETF EUR Acc. (DE),101.7340,5.7833,17.8503,-26.7745,0.16000,3.299020
IE00B53HP851,iShares Core FTSE 100 UCITS ETF GBP Acc.,82.7526,5.3195,14.1457,-12.9337,0.09000,3.251632

INFO:src.scrappy:Using short_term strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking

short_term

INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,28.4629,1.3867,17.7116,-16.0140,0.092,3.130972
FR0010655712,Amundi ETF DAX UCITS ETF DR EUR Acc.,28.5091,1.3869,17.7421,-16.0156,0.100,3.124365
DE0005933931,iShares Core DAX UCITS ETF EUR Acc. (DE),28.3669,1.4024,17.8238,-16.0187,0.160,3.065811
IE00BDFGJ627,iShares USD Floating Rate Bond UCITS ETF USD Acc.,0.8872,6.8837,0.2889,-0.1726,0.100,3.056123
LU0252633754,Amundi DAX III UCITS ETF EUR Acc.,28.3984,1.1076,22.1168,-16.0226,0.150,2.925532
IE0000X2DXK3,iShares iBonds Dec 2025 Term Corp UCITS ETF US...,0.8962,5.8575,0.3579,-0.0811,0.120,2.889655
LU1681040900,Amundi Floating Rate USD Corporate ESG UCITS E...,0.8833,5.1650,0.3739,-0.3391,0.180,2.744686
IE00BYVQ9F29,iShares NASDAQ-100 UCITS ETF EUR Acc. Hedged,27.7456,0.2690,28.6151,-22.7034,0.360,2.629537
IE00BM67HX07,Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged,13.9916,0.3604,19.0816,-18.7968,0.091,2.607411
IE00BDFK1573,iShares USD Treasury Bond 1-3 years UCITS ETF ...,17.8741,0.0270,17.1103,-11.9277,0.100,2.514660

In [42]:
favs = ['IE00BCRY6557', # iShares EUR Ultrashort Bond UCITS ETF Dis.
        'IE000NBRE3P7', # iShares EUR Ultrashort Bond ESG UCITS ETF EUR Acc.
        'LU1109942653', # Xtrackers II EUR High Yield Corporate Bond UCITS ETF 1D Dis.
        'LU1109943388', # Xtrackers II EUR High Yield Corporate Bond UCITS ETF 1C Acc.
        'DE000ETFL474', # Deka Oekom Euro Nachhaltigkeit UCITS ETF EUR Dis.
        'LU0274211480', # Xtrackers DAX UCITS ETF 1C EUR Acc.
        'DE000A0F5UF5', # iShares NASDAQ-100 UCITS ETF USD Dis. (DE)
        'IE00B53SZB19', # iShares NASDAQ-100 UCITS ETF USD Acc.
        'IE00BFY0GT14', # SPDR MSCI World UCITS ETF USD Acc.
        'IE00BM67HX07', # Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged
    ]

invest_sparplan = ['IE00BCRY6557', 'IE000NBRE3P7', 'LU1109942653', 'LU1109943388', 'DE000ETFL474', 'IE00B53SZB19']
invest = ['IE000UI6SLV6']


# s.download_timeseries(favs)
# s.save_timeseries('data/timeseries.csv')

display(s.filter_funds(isins=favs))

s.plot_correlations(favs)

s.plot_timeseries(invest+benchmarks, transform='yesterday', name_column='name')

WARNING:src.scrappy:ISINs not found: {'IE000NBRE3P7'}

,name,type,investment_focus,region,issuer,benchmark,country,currency,volume,fund_type,...,all_in_fee,currency_fee,depot_bank_fee,switching_fee,distribution_fee,redemption_fee,min_initial_investment,min_followup_investment,sparplan_finanzen_zero,finanzen_zero
isin,,,,,,,,,,,,,,,,,,,,,
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,ETF,Aktien Deutschland,Euroland,DWS,DAX,Luxemburg,EUR,6.373720e+09,Thesaurierend,...,0.09,NaN,NaN,1.0,0.0,0.0,NaN,NaN,True,True
IE00BM67HX07,Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged,ETF,Aktien USA,Nordamerika,DWS,S&P 500,Irland,GBP,1.132160e+09,Thesaurierend,...,0.09,NaN,NaN,3.0,0.0,0.0,NaN,NaN,True,True
IE00B53SZB19,iShares NASDAQ-100 UCITS ETF USD Acc.,ETF,Aktien USA,Nordamerika,BlackRock,NASDAQ 100,Irland,USD,1.867861e+10,Thesaurierend,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,True,True
DE000A0F5UF5,iShares NASDAQ-100 UCITS ETF USD Dis. (DE),ETF,Aktien USA,Nordamerika,BlackRock,NASDAQ 100,Deutschland,USD,4.739667e+09,Ausschüttend,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,True,True
IE00BFY0GT14,SPDR MSCI World UCITS ETF USD Acc.,ETF,Aktien International,International,SSGA,MSCI World,Irland,USD,1.264668e+10,Thesaurierend,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,True,True
DE000ETFL474,Deka Oekom Euro Nachhaltigkeit UCITS ETF EUR Dis.,ETF,"Aktien Ethik, Nachhaltigkeit",Euroland,Deka,SOLACTIVE EURO PRIME ESG (PREISINDEX),Deutschland,EUR,3.427688e+08,Ausschüttend,...,NaN,NaN,0.0238,NaN,NaN,0.0,NaN,NaN,True,True
LU1109943388,Xtrackers II EUR High Yield Corporate Bond UCI...,ETF,Renten International High Yield,International,DWS,MARKIT IBOXX EUR LIQUID HIGH YIELD INDEX,Luxemburg,EUR,1.614104e+09,Thesaurierend,...,0.20,NaN,NaN,1.0,0.0,0.0,NaN,NaN,True,True
LU1109942653,Xtrackers II EUR High Yield Corporate Bond UCI...,ETF,Renten EUR,International,DWS,MARKIT IBOXX EUR LIQUID HIGH YIELD INDEX,Luxemburg,EUR,1.614104e+09,Ausschüttend,...,0.20,NaN,NaN,1.0,0.0,0.0,NaN,NaN,True,True
IE00BCRY6557,iShares EUR Ultrashort Bond UCITS ETF Dis.,ETF,Renten Europa,International,BlackRock,MARKIT IBOXX EUR LIQUID INVESTMENT GRADE ULTRA...,Irland,EUR,4.423304e+09,Ausschüttend,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,True,True

WARNING:src.scrappy:Not in timeseries: ['IE000UI6SLV6']

In [3]:
# search by regex
esg_funds = s.search_funds_by_pattern('ESG|Sustainable|Green', column='name')
# esg_funds.head()

# s.filter_funds(benchmarks)

# s.extract_performance()

# s.filter_top_performers(by='sharpeRatio', timespan='1Y', limit=10)

# s.plot_timeseries(benchmarks, transform='2020-01-01')

# s.plot_correlations(benchmarks)

s.plot_risk_return(benchmarks)

# s.plot_benchmark_comparison(benchmarks)

# s.plot_benchmark_comparison(benchmarks, plot_difference=True)

KeyError: ['return', 'volatility']

In [17]:
s.save_funds_overview('data/funds_overview_test.csv')
s.save_performance('data/performance_test.csv')
s.save_timeseries('data/timeseries_test.csv')

In [23]:
s.ts.interpolate('time')

,AT0000497409,AT0000497417,AT0000604384,AT0000613286,AT0000619358,AT0000631924,AT0000639430,AT0000642343,AT0000645973,AT0000646799,...,LU2355687216,LU2363199626,LU2363200226,LU2363200499,LU2368674631,LU2368889163,NL0000289783,NL0009690254,NL0010273801,NL0010408704
x,,,,,,,,,,,,,,,,,,,,,
1938-02-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1938-02-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1938-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1938-03-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.69,NaN,NaN,NaN
1938-03-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.69,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-19,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82
2025-05-20,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82
2025-05-21,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82
2025-05-22,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82
2025-05-23,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82