In [11]:
%load_ext autoreload
%autoreload 2

from src.scrappy import Scrappy

s = Scrappy(
        funds_overview_path='data/funds_overview.csv',
        performance_path='data/performance.csv',
        timeseries_path='data/timeseries.csv'
    )

benchmarks = ['IE00B5BMR087', 'DE000A0F5UF5', 'IE0005042456', 'DE0006289390', 'DE0005933931', 'LU0340285161']

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

INFO:src.scrappy:Loaded funds_overview data from data/funds_overview.csv
INFO:src.scrappy:Loaded performance data from data/performance.csv
INFO:src.scrappy:Loaded timeseries data from data/timeseries.csv

In [12]:
renten_eu = [5531,5674,5676,5673,5647,5646,5620,5576,5670,5677]
s.download_funds_overview(benchmark=True)
s.download_funds_overview(limit=2000, etf=False)
s.download_funds_overview(limit=1000, etf=True)
s.download_funds_overview(limit=1000, filter_ids=renten_eu, etf=False)
s.download_funds_overview(limit=1000, filter_ids=renten_eu, etf=True)

s.extract_performance()

s.save_funds_overview('data/funds_overview.csv')
s.save_performance('data/performance.csv')

INFO:src.scrappy:Successfully downloaded 55 funds
/home/igor/git/scrappy/src/scrappy.py:514: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.funds_overview['finanzen_zero'] = self.funds_overview['finanzen_zero'].fillna(False).infer_objects(copy=False)
INFO:src.scrappy:Successfully downloaded 1940 funds
/home/igor/git/scrappy/src/scrappy.py:514: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.funds_overview['finanzen_zero'] = self.funds_overview['finanzen_zero'].fillna(False).infer_objects(copy=False)
INFO:src.scrappy:Successfully downloaded 201 funds
/home/igor/git/scrappy/src/scrappy.py:514: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.funds_overview['finanzen_zero'] = self.funds_overview['finanzen_zero'].fillna(False).infer_objects(copy=False)
INFO:src.scrappy:Successfully downloaded 642 funds
/home/igor/git/scrappy/src/scrappy.py:514: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.funds_overview['finanzen_zero'] = self.funds_overview['finanzen_zero'].fillna(False).infer_objects(copy=False)
INFO:src.scrappy:Successfully downloaded 152 funds
/home/igor/git/scrappy/src/scrappy.py:514: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.funds_overview['finanzen_zero'] = self.funds_overview['finanzen_zero'].fillna(False).infer_objects(copy=False)

In [3]:
s.download_timeseries(benchmarks)
s.save_timeseries('data/timeseries.csv')

INFO:src.scrappy:Parsing timeseries data...
WARNING:src.scrappy:Failed to parse data for IE00B5BMR087: malformed node or string on line 1: <ast.Call object at 0x7ddc91a0f710>, use eval
WARNING:src.scrappy:Failed to parse data for DE000A0F5UF5: malformed node or string on line 1: <ast.Call object at 0x7ddc92651350>, use eval
WARNING:src.scrappy:Failed to parse data for IE0005042456: malformed node or string on line 1: <ast.Call object at 0x7ddc937655d0>, use eval
WARNING:src.scrappy:Failed to parse data for DE0006289390: malformed node or string on line 1: <ast.Call object at 0x7ddc91eb3ed0>, use eval
WARNING:src.scrappy:Failed to parse data for DE0005933931: malformed node or string on line 1: <ast.Call object at 0x7ddc8d5c3310>, use eval
WARNING:src.scrappy:Failed to parse data for LU0340285161: malformed node or string on line 1: <ast.Call object at 0x7ddc902be150>, use eval

In [27]:
criteria = {'performanceTimeSpanPct': 0.0, 
            'sharpeRatio': 2.0, 
            'volatility': -0.0, 
            'maxDrawdown': -0.0, 
            'TER': -0.0}
s.rank_funds(criteria=criteria, timespan='5Y', sparplan_only=True, limit=20)

INFO:src.scrappy:Using pre-extracted performance data for ranking

INFO:src.scrappy:Ranked 20 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
IE00BCRY6557,iShares EUR Ultrashort Bond UCITS ETF Dis.,8.9712,41.7468,0.2524,-1.2539,0.090000,2.000000
IE00B3FH7618,iShares EUR Government Bond 0-1 year UCITS ETF...,5.4141,28.0288,0.2462,-2.1513,0.070000,1.382674
LU1109939865,Xtrackers II EUR High Yield Corporate Bond 1-3...,22.3797,10.5883,2.3422,-8.1566,0.300000,0.597831
DE000ETFL474,Deka Oekom Euro Nachhaltigkeit UCITS ETF EUR Dis.,154.2560,8.6435,19.5813,-29.6450,0.403446,0.510313
LU1109942653,Xtrackers II EUR High Yield Corporate Bond UCI...,24.3416,8.1980,3.2957,-14.7758,0.233000,0.490265
IE00B57X3V84,iShares Dow Jones Global Sustainability Screen...,82.6097,6.5631,14.2208,-27.3334,0.600000,0.416693
IE00BFY0GT14,SPDR MSCI World UCITS ETF USD Acc.,90.5183,6.5235,14.9727,-25.9038,0.120000,0.414911
IE00BK1PV551,Xtrackers MSCI World UCITS ETF 1D USD Dis.,89.8642,6.4489,15.0403,-26.0921,0.123000,0.411554
IE00BJ0KDQ92,Xtrackers MSCI World UCITS ETF 1C USD Acc.,89.5117,6.4273,15.0355,-26.0896,0.193000,0.410582
IE00B5BMR087,iShares Core S&P 500 UCITS ETF USD Acc.,100.8820,6.1955,17.8239,-24.6153,0.070000,0.400150
IE00B3XXRP09,Vanguard S&P 500 UCITS ETF USD Dis.,100.7850,6.1717,17.4780,-24.6165,0.070070,0.399079
IE00BFMXXD54,Vanguard S&P 500 UCITS ETF USD Acc.,100.7830,6.1717,17.4780,-24.6166,0.070070,0.399079
IE00B6YX5C33,SPDR S&P 500 UCITS ETF USD Dis.,101.4430,6.1629,17.4673,-24.6148,0.030000,0.398683
IE00BZ02LR44,Xtrackers MSCI World ESG UCITS ETF 1C USD Acc.,89.9316,6.1575,15.6578,-28.9594,0.200000,0.398440
IE00BG11HV38,iShares MSCI World ESG Enhanced UCITS ETF USD ...,82.6623,6.0328,15.3930,-28.0007,0.200000,0.392829
IE00BHZPJ569,iShares MSCI World ESG Enhanced UCITS ETF USD ...,82.4912,6.0206,15.3977,-28.0188,0.200000,0.392280
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,102.5980,5.8768,17.8847,-26.7592,0.092000,0.385808
FR0010655712,Amundi ETF DAX UCITS ETF DR EUR Acc.,102.2950,5.8196,18.0073,-26.7774,0.100000,0.383234
DE0009847343,terrAssisi Aktien I AMI - P EUR DIS,78.5839,5.7836,13.8467,-20.4308,1.352800,0.381614
DE0005933931,iShares Core DAX UCITS ETF EUR Acc. (DE),101.7340,5.7833,17.8503,-26.7745,0.160000,0.381601

In [6]:
# rank by strategies

print("conservative")
display(s.rank_funds_by_strategy(timespan='5Y', sparplan_only=True, strategy='conservative'))
print("growth")
display(s.rank_funds_by_strategy(timespan='5Y', sparplan_only=True, strategy='growth'))
print("balanced")
display(s.rank_funds_by_strategy(timespan='5Y', sparplan_only=True, strategy='balanced'))
print("long_term")
display(s.rank_funds_by_strategy(timespan='5Y', sparplan_only=True, strategy='long_term'))
print("short_term")
display(s.rank_funds_by_strategy(timespan='1Y', sparplan_only=True, strategy='short_term'))

INFO:src.scrappy:Using conservative strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking
INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

conservative

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
IE00BCRY6557,iShares EUR Ultrashort Bond UCITS ETF Dis.,8.9712,41.7468,0.2524,-1.2539,0.090,3.297916
IE00B3FH7618,iShares EUR Government Bond 0-1 year UCITS ETF...,5.4141,28.0288,0.2462,-2.1513,0.070,3.013341
LU1109942653,Xtrackers II EUR High Yield Corporate Bond UCI...,24.3416,8.1980,3.2957,-14.7758,0.233,2.787924
LU1287023268,Amundi Euro Government Bond 15+ years UCITS ET...,-31.9118,-2.1673,14.0786,-46.0075,0.150,2.784115
IE00BFNNN236,WisdomTree AT1 CoCo Bond UCITS ETF EUR Dis. He...,16.2238,2.3719,8.6176,-29.1502,0.390,2.734329
LU0950674332,UBS ETF MSCI World Socially Responsible UCITS ...,80.7660,5.5386,16.0520,-32.5243,0.220,2.712446
IE00B1XNHC34,iShares Global Clean Energy UCITS ETF USD Dis.,8.0041,0.6280,27.0834,-66.4785,0.650,2.712440
LU0629459743,UBS ETF MSCI World Socially Responsible UCITS ...,80.7414,5.5359,16.0522,-32.5272,0.220,2.712398
DE000A0D8Q31,"iShares eb.rexx Government Germany 10,5+ years...",-34.5226,-2.5676,12.8612,-41.8349,0.160,2.705469
IE00BZ02LR44,Xtrackers MSCI World ESG UCITS ETF 1C USD Acc.,89.9316,6.1575,15.6578,-28.9594,0.200,2.669014

INFO:src.scrappy:Using growth strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking
INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

growth

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
DE000ETFL474,Deka Oekom Euro Nachhaltigkeit UCITS ETF EUR Dis.,154.256,8.6435,19.5813,-29.6450,0.403446,3.151252
IE00BYVQ9F29,iShares NASDAQ-100 UCITS ETF EUR Acc. Hedged,136.172,4.2649,24.7371,-37.6626,0.360000,2.877232
DE000A0F5UF5,iShares NASDAQ-100 UCITS ETF USD Dis. (DE),123.104,5.3167,23.7767,-35.3696,0.310000,2.769721
IE00B53SZB19,iShares NASDAQ-100 UCITS ETF USD Acc.,123.478,5.3329,23.9418,-35.2751,0.330000,2.765832
IE00BM67HX07,Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged,109.777,5.4712,17.6155,-25.9211,0.091000,2.690262
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,102.598,5.8768,17.8847,-26.7592,0.092000,2.626464
IE00B6YX5C33,SPDR S&P 500 UCITS ETF USD Dis.,101.443,6.1629,17.4673,-24.6148,0.030000,2.626393
FR0010655712,Amundi ETF DAX UCITS ETF DR EUR Acc.,102.295,5.8196,18.0073,-26.7774,0.100000,2.618478
IE00B3XXRP09,Vanguard S&P 500 UCITS ETF USD Dis.,100.785,6.1717,17.4780,-24.6165,0.070070,2.608203
IE00BFMXXD54,Vanguard S&P 500 UCITS ETF USD Acc.,100.783,6.1717,17.4780,-24.6166,0.070070,2.608182

INFO:src.scrappy:Using balanced strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking
INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

balanced

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
IE00BCRY6557,iShares EUR Ultrashort Bond UCITS ETF Dis.,8.9712,41.7468,0.2524,-1.2539,0.090000,3.710879
IE00B3FH7618,iShares EUR Government Bond 0-1 year UCITS ETF...,5.4141,28.0288,0.2462,-2.1513,0.070000,3.095083
DE000ETFL474,Deka Oekom Euro Nachhaltigkeit UCITS ETF EUR Dis.,154.2560,8.6435,19.5813,-29.6450,0.403446,2.820808
IE00BFY0GT14,SPDR MSCI World UCITS ETF USD Acc.,90.5183,6.5235,14.9727,-25.9038,0.120000,2.542056
IE00BM67HX07,Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged,109.7770,5.4712,17.6155,-25.9211,0.091000,2.537406
IE00BK1PV551,Xtrackers MSCI World UCITS ETF 1D USD Dis.,89.8642,6.4489,15.0403,-26.0921,0.123000,2.535390
IE00BYVQ9F29,iShares NASDAQ-100 UCITS ETF EUR Acc. Hedged,136.1720,4.2649,24.7371,-37.6626,0.360000,2.530429
IE00B6YX5C33,SPDR S&P 500 UCITS ETF USD Dis.,101.4430,6.1629,17.4673,-24.6148,0.030000,2.527901
IE00BZ02LR44,Xtrackers MSCI World ESG UCITS ETF 1C USD Acc.,89.9316,6.1575,15.6578,-28.9594,0.200000,2.525649
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,102.5980,5.8768,17.8847,-26.7592,0.092000,2.523135

INFO:src.scrappy:Using long_term strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking
INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

long_term

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
IE00BCRY6557,iShares EUR Ultrashort Bond UCITS ETF Dis.,8.9712,41.7468,0.2524,-1.2539,0.090000,4.127995
DE000ETFL474,Deka Oekom Euro Nachhaltigkeit UCITS ETF EUR Dis.,154.2560,8.6435,19.5813,-29.6450,0.403446,3.698083
IE00B3FH7618,iShares EUR Government Bond 0-1 year UCITS ETF...,5.4141,28.0288,0.2462,-2.1513,0.070000,3.668242
IE00B6YX5C33,SPDR S&P 500 UCITS ETF USD Dis.,101.4430,6.1629,17.4673,-24.6148,0.030000,3.557336
IE00BM67HX07,Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged,109.7770,5.4712,17.6155,-25.9211,0.091000,3.549584
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,102.5980,5.8768,17.8847,-26.7592,0.092000,3.521815
IE00B3XXRP09,Vanguard S&P 500 UCITS ETF USD Dis.,100.7850,6.1717,17.4780,-24.6165,0.070070,3.520995
IE00BFMXXD54,Vanguard S&P 500 UCITS ETF USD Acc.,100.7830,6.1717,17.4780,-24.6166,0.070070,3.520983
IE00B5BMR087,iShares Core S&P 500 UCITS ETF USD Acc.,100.8820,6.1955,17.8239,-24.6153,0.070000,3.517303
FR0010655712,Amundi ETF DAX UCITS ETF DR EUR Acc.,102.2950,5.8196,18.0073,-26.7774,0.100000,3.509874

INFO:src.scrappy:Using short_term strategy for ranking
INFO:src.scrappy:Using pre-extracted performance data for ranking
INFO:src.scrappy:Ranked 10 funds using criteria: ['performanceTimeSpanPct', 'sharpeRatio', 'volatility', 'maxDrawdown', 'TER']

short_term

,name,performanceTimeSpanPct,sharpeRatio,volatility,maxDrawdown,TER,score
isins,,,,,,,
LU2611732046,Amundi DAX UCITS ETF EUR Dis.,28.4718,1.3847,17.7413,-16.0109,0.080,4.006946
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,28.4629,1.3867,17.7116,-16.0140,0.092,4.005868
FR0010655712,Amundi ETF DAX UCITS ETF DR EUR Acc.,28.5091,1.3869,17.7421,-16.0156,0.100,4.005049
LU1349386927,Xtrackers DAX UCITS ETF 1D EUR Dis.,28.4469,1.3858,17.7110,-16.0143,0.092,4.005044
DE0005933931,iShares Core DAX UCITS ETF EUR Acc. (DE),28.3669,1.4024,17.8238,-16.0187,0.160,3.992507
DE000A2QP331,iShares Core DAX UCITS ETF EUR Dis. (DE),28.3697,1.3738,17.8119,-16.0177,0.160,3.981817
IE00BG143G97,Vanguard Germany All Cap UCITS ETF EUR Dis.,27.5885,1.3725,17.3019,-15.7532,0.101,3.973946
LU0838782315,Xtrackers DAX ESG Screened UCITS ETF 1D EUR Dis.,23.4553,1.1356,17.3143,-16.7819,0.091,3.785163
LU0252633754,Amundi DAX III UCITS ETF EUR Acc.,28.3984,1.1076,22.1168,-16.0226,0.150,3.772558
LU2090062436,Amundi DAX III UCITS ETF EUR Dis.,28.3984,1.1076,22.1169,-16.0226,0.150,3.772556

In [67]:
favs = ['IE00BCRY6557', # iShares EUR Ultrashort Bond UCITS ETF Dis.
        'IE000NBRE3P7', # iShares EUR Ultrashort Bond ESG UCITS ETF EUR Acc.
        'LU1109942653', # Xtrackers II EUR High Yield Corporate Bond UCITS ETF 1D Dis.
        'LU1109943388', # Xtrackers II EUR High Yield Corporate Bond UCITS ETF 1C Acc.
        'DE000ETFL474', # Deka Oekom Euro Nachhaltigkeit UCITS ETF EUR Dis.
        'LU0274211480', # Xtrackers DAX UCITS ETF 1C EUR Acc.
        'DE000A0F5UF5', # iShares NASDAQ-100 UCITS ETF USD Dis. (DE)
        'IE00B53SZB19', # iShares NASDAQ-100 UCITS ETF USD Acc.
        'IE00BFY0GT14', # SPDR MSCI World UCITS ETF USD Acc.
        'IE00BM67HX07', # Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged
    ]

invest_sparplan = ['IE00BCRY6557', 'IE000NBRE3P7', 'LU1109942653', 'LU1109943388', 'DE000ETFL474', 'IE00B53SZB19']
invest = ['IE000UI6SLV6']


# s.download_timeseries(favs)
# s.save_timeseries('data/timeseries.csv')

display(s.filter_funds(favs))

s.plot_correlations(favs)

s.plot_timeseries(invest+benchmarks, transform='yesterday', name_column='name')

WARNING:src.scrappy:Not found: ['IE000NBRE3P7', 'LU1109943388']

,name,type,investment_focus,region,issuer,benchmark,country,currency,volume,fund_type,...,all_in_fee,currency_fee,depot_bank_fee,switching_fee,distribution_fee,redemption_fee,min_initial_investment,min_followup_investment,sparplan_finanzen_zero,finanzen_zero
isin,,,,,,,,,,,,,,,,,,,,,
LU0274211480,Xtrackers DAX UCITS ETF 1C EUR Acc.,ETF,Aktien Deutschland,Euroland,DWS,DAX,Luxemburg,EUR,6.373720e+09,Thesaurierend,...,0.09,NaN,NaN,1.0,0.0,0.0,NaN,NaN,True,True
IE00BM67HX07,Xtrackers S&P 500 UCITS ETF 2C GBP Acc. Hedged,ETF,Aktien USA,Nordamerika,DWS,S&P 500,Irland,GBP,1.132160e+09,Thesaurierend,...,0.09,NaN,NaN,3.0,0.0,0.0,NaN,NaN,True,True
IE00B53SZB19,iShares NASDAQ-100 UCITS ETF USD Acc.,ETF,Aktien USA,Nordamerika,BlackRock,NASDAQ 100,Irland,USD,1.848222e+10,Thesaurierend,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,True,True
DE000A0F5UF5,iShares NASDAQ-100 UCITS ETF USD Dis. (DE),ETF,Aktien USA,Nordamerika,BlackRock,NASDAQ 100,Deutschland,USD,4.672869e+09,Ausschüttend,...,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,True,True
IE00BFY0GT14,SPDR MSCI World UCITS ETF USD Acc.,ETF,Aktien International,International,SSGA,MSCI World,Irland,USD,1.241098e+10,Thesaurierend,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,True,True
DE000ETFL474,Deka Oekom Euro Nachhaltigkeit UCITS ETF EUR Dis.,ETF,"Aktien Ethik, Nachhaltigkeit",Euroland,Deka,SOLACTIVE EURO PRIME ESG (PREISINDEX),Deutschland,EUR,3.405503e+08,Ausschüttend,...,NaN,NaN,0.0238,NaN,NaN,1.0,NaN,NaN,True,True
LU1109942653,Xtrackers II EUR High Yield Corporate Bond UCI...,ETF,Renten EUR,International,DWS,MARKIT IBOXX EUR LIQUID HIGH YIELD INDEX,Luxemburg,EUR,1.614104e+09,Ausschüttend,...,0.20,NaN,NaN,1.0,0.0,0.0,NaN,NaN,True,True
IE00BCRY6557,iShares EUR Ultrashort Bond UCITS ETF Dis.,ETF,Renten Europa,International,BlackRock,MARKIT IBOXX EUR LIQUID INVESTMENT GRADE ULTRA...,Irland,EUR,4.412118e+09,Ausschüttend,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,True,True

In [3]:
# search by regex
esg_funds = s.search_funds_by_pattern('ESG|Sustainable|Green', column='name')
# esg_funds.head()

# s.filter_funds(benchmarks)

# s.extract_performance()

# s.filter_top_performers(by='sharpeRatio', timespan='1Y', limit=10)

# s.plot_timeseries(benchmarks, transform='2020-01-01')

# s.plot_correlations(benchmarks)

s.plot_risk_return(benchmarks)

# s.plot_benchmark_comparison(benchmarks)

# s.plot_benchmark_comparison(benchmarks, plot_difference=True)

KeyError: ['return', 'volatility']

In [17]:
s.save_funds_overview('data/funds_overview_test.csv')
s.save_performance('data/performance_test.csv')
s.save_timeseries('data/timeseries_test.csv')

In [23]:
s.ts.interpolate('time')

,AT0000497409,AT0000497417,AT0000604384,AT0000613286,AT0000619358,AT0000631924,AT0000639430,AT0000642343,AT0000645973,AT0000646799,...,LU2355687216,LU2363199626,LU2363200226,LU2363200499,LU2368674631,LU2368889163,NL0000289783,NL0009690254,NL0010273801,NL0010408704
x,,,,,,,,,,,,,,,,,,,,,
1938-02-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1938-02-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1938-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1938-03-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.69,NaN,NaN,NaN
1938-03-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.69,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-19,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82
2025-05-20,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82
2025-05-21,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82
2025-05-22,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82
2025-05-23,131.63,131.62,156.05,15.56,17.52,181.17,181.21,206.26,176.03,535.61,...,92.57,97.19,97.19,97.34,15.52,91.57,144.69,17.3,25.45,35.82